---
name: Services

on: [push]

jobs:
  build-test:
    name: "Build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        working-directory: services
        run: go build -v ./...

      - name: Test
        working-directory: services
        run: go test -v ./...
